# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-efs
  description: Terraform Module to define an EFS Filesystem (aka NFS)
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-modules, efs, aws, nfs, hcl2
